services:
  db:
    image: postgis/postgis:16-3.4
    env_file: .env
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./backend
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file: .env
    depends_on: [db]
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports: ["8000:8000"]

  load-data:
    build: ./backend
    env_file: .env
    depends_on: [ db ]
    volumes:
      - ./backend:/app
      - ./data:/data:ro
    command: >
      python -m etl.sheet_insertion /db/data/assumable_properties.xlsx

  redis:
    image: redis:7-alpine

volumes:
  db_data:
